# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='广告名')),
                ('callback_url', models.URLField(verbose_name='广告链接')),
                ('adimg', models.ImageField(default='normal.png', upload_to='img/ad', verbose_name='广告图片')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stonumber', models.CharField(max_length=20, verbose_name='股票编码')),
                ('company_name', models.CharField(max_length=50, verbose_name='公司名称')),
                ('industry', models.CharField(max_length=50, null=True, verbose_name='细分行业')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='地区')),
                ('pe', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='市盈率')),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='流通股本')),
                ('totals', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总股本')),
                ('totalAssets', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总资产')),
                ('liquidAssets', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='流动资产')),
                ('fixAssets', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='固定资产')),
                ('reserved', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='公积金')),
                ('reservedPerShare', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股公积金')),
                ('esp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股收益')),
                ('bvps', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每股净资')),
                ('pb', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='市净率')),
                ('timeToMarket', models.DateField(verbose_name='上市日期')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
